# kind create cluster --name k8s-cluster --config kind-config.yml
# kind delete cluster --name k8s-cluster
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: false
nodes:
  - role: control-plane
  - role: worker
  - role: worker